### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by janakajm** [Mozenn/spring-boot-keycloak-admin-api#1]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project spring-boot-keycloak-admin-api: Fatal error comp
iling: invalid target release: 17 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Mozenn** [comment]
This is caused by using the wrong Java version. You should be using Java 17, and update your JAVA_HOME environment variable as explained here https://mkyong.com/maven/maven-error-invalid-target-release-17/
